/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */
import type { ArticleSummaryResponseDtoWithHeadlineCategory } from "./articleSummaryResponseDtoWithHeadlineCategory";
import type { MediaDto } from "./mediaDto";
import type { CompanySummaryResponseDto } from "./companySummaryResponseDto";

export type ArticleSummaryResponseDtoWithHeadline = {
  /** 뉴스 ID */
  uuid: string;
  /** 뉴스 제목 */
  title: string;
  /** 뉴스 내용 */
  contents: string;
  /**
   * 뉴스 카테고리
   * @nullable
   */
  category: ArticleSummaryResponseDtoWithHeadlineCategory;
  /** 생성일 */
  createAt: string;
  /** 미디어 정보 */
  media: MediaDto;
  /** 헤드라인 여부 */
  isHeadline: boolean;
  /** 언론사 */
  company: CompanySummaryResponseDto;
};
