/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */
import type { MediaDto } from "./mediaDto";

export type ArticleSearch = {
  /** 뉴스 UUID */
  uuid: string;
  /** 뉴스 제목 */
  title: string;
  /** 뉴스 요약 내용 */
  contents: string;
  /** 미디어 정보 */
  media?: MediaDto;
};
