/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */

export type ArticleControllerFindArticleByCategoryParams = {
  /**
   * 페이지 번호
   */
  page?: number;
  /**
   * 한 페이지에 표시할 항목 수
   */
  limit?: number;
};
