/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */
import type { CompanySummaryResponseDto } from "./companySummaryResponseDto";

export type ArticleResponseDto = {
  /** 뉴스 ID */
  uuid: string;
  /** 뉴스 제목 */
  title: string;
  /** 뉴스 내용 */
  contents: string[];
  /** 생성일 */
  createAt: string;
  originalUrl: string;
  /** 언론사 */
  company: CompanySummaryResponseDto;
};
