/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */

export type ChangeEmailDto = {
  /** 기존 이메일 */
  originalEmail: string;
  /** 변경할 이메일 */
  newEmail: string;
};
