/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */

export type CompanyResponseDto = {
  uuid: string;
  profileImageUrl: string;
  name: string;
  description: string;
  subscribers: number;
  signatureColor: string;
};
