/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */
import type { Subject } from "./subject";
import type { Description } from "./description";
import type { Footnote } from "./footnote";
import type { List } from "./list";
import type { Link } from "./link";
import type { Scroll } from "./scroll";
import type { MediaContent } from "./mediaContent";

export type CreateArticleDtoContentsItem =
  | Subject
  | Description
  | Footnote
  | List
  | Link
  | Scroll
  | MediaContent;
