/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */
import type { CreateArticleDtoContentsItem } from "./createArticleDtoContentsItem";
import type { SummaryDto } from "./summaryDto";

export type CreateArticleDto = {
  category: string;
  title: string;
  contents: CreateArticleDtoContentsItem[];
  summary: SummaryDto;
  createdAt: string;
  isHeadline: boolean;
  companyId: string;
  originalUrl: string;
};
