/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */

export type EmailVerifyDto = {
  /** 이메일 */
  email: string;
  /** 이메일 인증 코드 */
  code: string;
};
