/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */

export type FootnoteType = (typeof FootnoteType)[keyof typeof FootnoteType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FootnoteType = {
  footnote: "footnote",
} as const;
