/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */
import type { FootnoteType } from "./footnoteType";

export type Footnote = {
  type: FootnoteType;
  id?: string;
  content: string;
};
