/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */

export type LinkType = (typeof LinkType)[keyof typeof LinkType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkType = {
  link: "link",
} as const;
