/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */
import type { MediaContentType } from "./mediaContentType";
import type { MediaContentMediaType } from "./mediaContentMediaType";

export type MediaContent = {
  type: MediaContentType;
  mediaType: MediaContentMediaType;
  url: string;
  description?: string;
};
