/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */

export type MediaContentType =
  (typeof MediaContentType)[keyof typeof MediaContentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaContentType = {
  media: "media",
} as const;
