/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */
import type { MediaDto } from "./mediaDto";
import type { CompanySummaryResponseDto } from "./companySummaryResponseDto";

export type Notification = {
  title: string;
  contents: string;
  media?: MediaDto;
  company: CompanySummaryResponseDto;
};
