/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */
import type { ArticleSummaryResponseDto } from "./articleSummaryResponseDto";

export type PaginatedArticleResponseSummaryDto = {
  /** 뉴스 목록 */
  items: ArticleSummaryResponseDto[];
  /** 전체 뉴스 개수 */
  total: number;
  /** 현재 페이지 */
  page: number;
  /** 페이지당 항목 수 */
  limit: number;
  /** 전체 페이지 수 */
  totalPages: number;
};
