/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */

export type ScrollType = (typeof ScrollType)[keyof typeof ScrollType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScrollType = {
  scroll: "scroll",
} as const;
