/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */

export type SignInDto = {
  /** 이메일 */
  email: string;
  /** 비밀번호 */
  password: string;
};
