/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */
import type { CompanySummaryResponseDto } from "./companySummaryResponseDto";

export type SubscribedCompaniesResponseDto = {
  /** 사용자가 구독한 언론사 목록 */
  items: CompanySummaryResponseDto[];
};
