/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Nexus Core Backend
 * The news viewer service, Nexus API Description
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  ChangeEmailDto,
  ChangePasswordDto,
  SubscribeCompanyDto,
} from "../../const";

import { customInstance } from "../../../shared/axios/lib/customInstance";
import type {
  ErrorType,
  BodyType,
} from "../../../shared/axios/lib/customInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary 이메일 변경
 */
export const userControllerChangeEmail = (
  changeEmailDto: BodyType<ChangeEmailDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    {
      url: `/user/change/email`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: changeEmailDto,
    },
    options,
  );
};

export const getUserControllerChangeEmailMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerChangeEmail>>,
    TError,
    { data: BodyType<ChangeEmailDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerChangeEmail>>,
  TError,
  { data: BodyType<ChangeEmailDto> },
  TContext
> => {
  const mutationKey = ["userControllerChangeEmail"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerChangeEmail>>,
    { data: BodyType<ChangeEmailDto> }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerChangeEmail(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerChangeEmailMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerChangeEmail>>
>;
export type UserControllerChangeEmailMutationBody = BodyType<ChangeEmailDto>;
export type UserControllerChangeEmailMutationError = ErrorType<unknown>;

/**
 * @summary 이메일 변경
 */
export const useUserControllerChangeEmail = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerChangeEmail>>,
      TError,
      { data: BodyType<ChangeEmailDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerChangeEmail>>,
  TError,
  { data: BodyType<ChangeEmailDto> },
  TContext
> => {
  const mutationOptions = getUserControllerChangeEmailMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 비밀번호 변경
 */
export const userControllerChangePassword = (
  changePasswordDto: BodyType<ChangePasswordDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    {
      url: `/user/change/password`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: changePasswordDto,
    },
    options,
  );
};

export const getUserControllerChangePasswordMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerChangePassword>>,
    TError,
    { data: BodyType<ChangePasswordDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerChangePassword>>,
  TError,
  { data: BodyType<ChangePasswordDto> },
  TContext
> => {
  const mutationKey = ["userControllerChangePassword"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerChangePassword>>,
    { data: BodyType<ChangePasswordDto> }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerChangePassword(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerChangePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerChangePassword>>
>;
export type UserControllerChangePasswordMutationBody =
  BodyType<ChangePasswordDto>;
export type UserControllerChangePasswordMutationError = ErrorType<unknown>;

/**
 * @summary 비밀번호 변경
 */
export const useUserControllerChangePassword = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerChangePassword>>,
      TError,
      { data: BodyType<ChangePasswordDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerChangePassword>>,
  TError,
  { data: BodyType<ChangePasswordDto> },
  TContext
> => {
  const mutationOptions =
    getUserControllerChangePasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 구독
 */
export const userControllerSubscribe = (
  subscribeCompanyDto: BodyType<SubscribeCompanyDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    {
      url: `/user/subscribe`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: subscribeCompanyDto,
    },
    options,
  );
};

export const getUserControllerSubscribeMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerSubscribe>>,
    TError,
    { data: BodyType<SubscribeCompanyDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerSubscribe>>,
  TError,
  { data: BodyType<SubscribeCompanyDto> },
  TContext
> => {
  const mutationKey = ["userControllerSubscribe"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerSubscribe>>,
    { data: BodyType<SubscribeCompanyDto> }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerSubscribe(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerSubscribeMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerSubscribe>>
>;
export type UserControllerSubscribeMutationBody = BodyType<SubscribeCompanyDto>;
export type UserControllerSubscribeMutationError = ErrorType<unknown>;

/**
 * @summary 구독
 */
export const useUserControllerSubscribe = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerSubscribe>>,
      TError,
      { data: BodyType<SubscribeCompanyDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerSubscribe>>,
  TError,
  { data: BodyType<SubscribeCompanyDto> },
  TContext
> => {
  const mutationOptions = getUserControllerSubscribeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 구독 해제
 */
export const userControllerUnsubscribeCompany = (
  subscribeCompanyDto: BodyType<SubscribeCompanyDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    {
      url: `/user/unsubscribe`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: subscribeCompanyDto,
    },
    options,
  );
};

export const getUserControllerUnsubscribeCompanyMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerUnsubscribeCompany>>,
    TError,
    { data: BodyType<SubscribeCompanyDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerUnsubscribeCompany>>,
  TError,
  { data: BodyType<SubscribeCompanyDto> },
  TContext
> => {
  const mutationKey = ["userControllerUnsubscribeCompany"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerUnsubscribeCompany>>,
    { data: BodyType<SubscribeCompanyDto> }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerUnsubscribeCompany(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerUnsubscribeCompanyMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUnsubscribeCompany>>
>;
export type UserControllerUnsubscribeCompanyMutationBody =
  BodyType<SubscribeCompanyDto>;
export type UserControllerUnsubscribeCompanyMutationError = ErrorType<unknown>;

/**
 * @summary 구독 해제
 */
export const useUserControllerUnsubscribeCompany = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerUnsubscribeCompany>>,
      TError,
      { data: BodyType<SubscribeCompanyDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerUnsubscribeCompany>>,
  TError,
  { data: BodyType<SubscribeCompanyDto> },
  TContext
> => {
  const mutationOptions =
    getUserControllerUnsubscribeCompanyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary 계정 삭제
 */
export const userControllerDeleteAccount = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/user/delete`, method: "DELETE" },
    options,
  );
};

export const getUserControllerDeleteAccountMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerDeleteAccount>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerDeleteAccount>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["userControllerDeleteAccount"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerDeleteAccount>>,
    void
  > = () => {
    return userControllerDeleteAccount(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerDeleteAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerDeleteAccount>>
>;

export type UserControllerDeleteAccountMutationError = ErrorType<unknown>;

/**
 * @summary 계정 삭제
 */
export const useUserControllerDeleteAccount = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerDeleteAccount>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerDeleteAccount>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions =
    getUserControllerDeleteAccountMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
